XaiphasInvestment/Ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'Ecommerce'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('add_stock/', views.add_stock, name='add_stock'),
    path('toggleactivate/<int:item_id>/',views.toggleactivate, name='toggleactivate'),
    path('edit_item/<int:item_id>/',views.edit_item, name='edit_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('stock_summary/', views.stock_summary, name='stock_summary'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('investment/', views.investment, name='investment'),
    path('transaction_log/', views.transaction_log, name='transaction_log'),
    path('profile/', views.profile, name='profile'),
    path('mpesa_deposit/', views.mpesa_deposit, name='mpesa_deposit'),

    # path('mpesa/' ,views.getAccessToken, name='mpesa'),
    # path('mpesa/lipa', views.lipa_na_mpesa_online, name='lipa_na_mpesa'),
    #
    # # register, confirmation, validation and callback urls
    # path('c2b/register', views.register_urls, name="register_mpesa_validation"),
    # path('c2b/confirmation', views.confirmation, name="confirmation"),
    # path('c2b/validation', views.validation, name="validation"),
    # path('c2b/callback', views.call_back, name="call_back"),

]

# path('checkout/', views.CheckoutView.as_view(), name='checkout'),
# path('OrderSummary/', views.OrderSummary.as_view(), name='order_summary'),
# path('product/<slug>/', views.ProductView.as_view(), name='product'),
# path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),
# path('a-s-t-t-c/<slug>/', views.add_single_item_to_cart, name='add_single_item_to_cart'),
# path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
# path('r-i-f-c/<slug>/', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
# path('payment/', views.PaymentView.as_view(), name='payment'),

XaiphasInvestment/XaiphasInvestments/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Ecommerce/', include('Ecommerce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XaiphasInvestment/Ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver


Category_choice = (
    ('Men', 'Men'),
    ('Women', 'Women'),
    ('Children', 'Children'),
)
Label_choice = (
    ('primary', 'primary'),
    ('secondary', 'secondary'),
    ('danger', 'danger'),
)


class Userprofile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE
    )
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(choices=Category_choice, max_length=200)
    slug = models.SlugField()
    image = models.ImageField()
    url = models.URLField()
    ShowCastToCustomers = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True,null=True)

    class Meta:
        abstract = True


class MpesaPayment(BaseModel):
    transaction_id = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    transaction_type = models.TextField()
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.TextField()

    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'

    def __str__(self):
        return self.first_name


class Wallet(models.Model):
    user_name = models.CharField(max_length=100, blank=True, null=True)
    available_balance = models.DecimalField(('available_balance'), max_digits=6, decimal_places=2, default=0)
    date_modified = models.DateTimeField(auto_now=True,blank=True ,null=True)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    def __str__(self):
        return self.user_name

XaiphasInvestment/Ecommerce/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django.contrib.auth.models import User
from .models import *

Payment_Choices = (
    ('Mpesa', 'Mpesa'),
    ('PayPal', 'Paypal'),
)


class AddStockForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['title', 'category', 'image','url']


class UserLogForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Email'}),
        }

XaiphasInvestment/Ecommerce/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.utils import timezone
from django.views.generic import ListView, DetailView, View
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .forms import *
from django.contrib.auth import login,logout,authenticate
import random

# from django.http import HttpResponse, JsonResponse
# import json
# from django.views.decorators.csrf import csrf_exempt
#
# from django.http import HttpResponse
# import requests
# from requests.auth import HTTPBasicAuth
# import json
# from . mpesa_credentials import MpesaAccessToken, LipanaMpesaPpassword
#
#
# def getAccessToken(request):
#     consumer_key = 'XJOD78XsSN9GYrBTuPJhtlySmwna21zo'
#     consumer_secret = 'oOE7NuQeXYu7DTJl'
#     api_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'
#
#     r = requests.get(api_URL, auth=HTTPBasicAuth(consumer_key, consumer_secret))
#     mpesa_access_token = json.loads(r.text)
#     validated_mpesa_access_token = mpesa_access_token['access_token']
#
#     return HttpResponse(validated_mpesa_access_token)
#
#
# def lipa_na_mpesa_online(request):
#     access_token = MpesaAccessToken.validated_mpesa_access_token
#     api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
#     headers = {"Authorization": "Bearer %s" % access_token}
#     request = {
#         "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
#         "Password": LipanaMpesaPpassword.decode_password,
#         "Timestamp": LipanaMpesaPpassword.lipa_time,
#         "TransactionType": "CustomerPayBillOnline",
#         "Amount": 1,
#         "PartyA": 254701628981,  # replace with your phone number to get stk push
#         "PartyB": LipanaMpesaPpassword.Business_short_code,
#         "PhoneNumber": 254701628981,  # replace with your phone number to get stk push
#         "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
#         "AccountReference": "Henry",
#         "TransactionDesc": "Testing stk push"
#     }
#     response = requests.post(api_url, json=request, headers=headers)
#     return HttpResponse('success')
#
#
# @csrf_exempt
# def register_urls(request):
#     access_token = MpesaAccessToken.validated_mpesa_access_token
#     api_url = "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
#     headers = {"Authorization": "Bearer %s" % access_token}
#     options = {"ShortCode": LipanaMpesaPpassword.Test_c2b_shortcode,
#                "ResponseType": "Completed",
#                "ConfirmationURL": "https://bcb733b45166.ngrok.io/Ecommerce/c2b/confirmation",
#                "ValidationURL": "https://bcb733b45166.ngrok.io/Ecommerce/c2b/validation"}
#     response = requests.post(api_url, json=options, headers=headers)
#     return HttpResponse(response.text)
#
#
# @csrf_exempt
# def call_back(request):
#     pass
#
#
# @csrf_exempt
# def validation(request):
#     context = {
#         "ResultCode": 0,
#         "ResultDesc": "Accepted"
#     }
#     return JsonResponse(dict(context))
#
#
# @csrf_exempt
# def confirmation(request):
#     mpesa_body =request.body.decode('utf-8')
#     mpesa_payment = json.loads(mpesa_body)
#     payment = MpesaPayment(
#         first_name=mpesa_payment['FirstName'],
#         last_name=mpesa_payment['LastName'],
#         middle_name=mpesa_payment['MiddleName'],
#         description=mpesa_payment['TransID'],
#         phone_number=mpesa_payment['MSISDN'],
#         amount=mpesa_payment['TransAmount'],
#         reference=mpesa_payment['BillRefNumber'],
#         organization_balance=mpesa_payment['OrgAccountBalance'],
#         type=mpesa_payment['TransactionType'],
#     )
#     payment.save()
#     context = {
#         "ResultCode": 0,
#         "ResultDesc": "Accepted"
#     }
#     return JsonResponse(dict(context))
#
#
#
#
#


def about(request):
    return render(request, 'Ecommerce/about_us.html')


def mpesa_deposit(request):
    return render(request, 'Ecommerce/mpesa_deposit.html')


def transaction_log(request):
    return render(request, 'Ecommerce/transaction_log.html')


def profile(request):
    user = User.objects.filter(pk=request.user.id)
    context = {
        'users': user,
    }
    return render(request, 'Ecommerce/profile.html', context)


def investment(request):
    if not request.user.is_authenticated:
        messages.warning(request, 'User is not authenticated.')
        return redirect('Ecommerce:login')
    else:
        return render(request, 'Ecommerce/investment.html')


def stock_summary(request):
    all_stock = Item.objects.all()
    context = {
        'all_stock': all_stock
    }
    return render(request, 'Ecommerce/item_collection.html', context)


def toggleactivate(request,item_id):
    item = Item.objects.get(pk=item_id)
    item.ShowCastToCustomers = not item.ShowCastToCustomers
    item.save()
    if item.ShowCastToCustomers is True:
        messages.info(request, 'Item Activated.')
    else:
        messages.warning(request, 'Item hidden.')
    return redirect('Ecommerce:stock_summary')


class HomeView(ListView):
    model = Item
    queryset = Item.objects.filter(ShowCastToCustomers=True)
    paginate_by = 8
    template_name = 'Ecommerce/home-page.html'


def add_stock(request):
    if request.user.username != 'admin':
        return redirect('Ecommerce:home')
    else:
        form=AddStockForm()
        if request.method == 'POST':
            form = AddStockForm(request.POST or None, request.FILES or None)
            print(request.POST)
            if form.is_valid():
                item = form.save(commit=False)
                title = form.cleaned_data.get('title')

                slid = random.randint(0, 100)
                item.image = request.FILES['image']
                item.slug = title.replace(' ','-')+'-'+str(slid)
                item.save()
                print('form is valid')

                messages.success(request, 'Item Added Successfully')
                return redirect('Ecommerce:home')
            else:
                messages.warning(request, 'Invalid URL try again.')
                context = {
                    'form': form,
                }
                return render(request, 'Ecommerce/Add_items.html', context)

        context = {
            'form': form,
        }
        return render(request, 'Ecommerce/Add_items.html', context)


def edit_item(request, item_id):
    if request.user.username != 'admin':
        return redirect('Ecommerce:home')
    else:
        item = Item.objects.get(pk=item_id)
        form = AddStockForm(instance=item)

        if request.method == 'POST':
            form = AddStockForm(request.POST, request.FILES or None, instance=item,)
            if form.is_valid():
                item.image = request.FILES['image']
                form.save()
                messages.success(request, 'Update Successful')
                return redirect('Ecommerce:stock_summary')
        context = {
            'title': 'Edit',
            'form': form,
        }
        return render(request, 'Ecommerce/edit_items.html', context)


def delete_item(request, item_id):
    if request.user.username != 'admin':
        return redirect('Ecommerce:home')
    else:

        item = Item.objects.get(pk=item_id)
        item.delete()
        messages.success(request, 'Delete Successful.')
        return redirect('Ecommerce:stock_summary')

@receiver(post_save, sender=MpesaPayment)
def update_wallet(sender, instance, created, **kwargs):
    try:
        if created:
           wallet= Wallet.objects.get(
                user_name=instance.phone_number,
            )
           wallet.available_balance+=instance.amount
           wallet.save()
    except ObjectDoesNotExist:
        return redirect('Ecommerce:investment')


@receiver(post_save, sender=User)
def create_wallet(sender,instance,created,**kwargs):
    if created:
        Wallet.objects.create(
            user_name=instance.username
        )























#
#
# class OrderSummary(View):
#     def get(self, *args, **kwargs):
#
#         try:
#             order = Order.objects.get(
#                 user=self.request.user,
#                 ordered=False
#             )
#             context = {
#                 'object': order
#             }
#             return render(self.request, 'Ecommerce/investment.html', context)
#         except ObjectDoesNotExist:
#             messages.warning(self.request, 'You do not have an active order.')
#             return redirect('Ecommerce:home')
#
#
# class ProductView(DetailView):
#     model = Item
#     template_name = 'Ecommerce/transaction_log.html'
#
#
# def add_to_cart(request, slug):
#     if not request.user.is_authenticated:
#         messages.warning(request, 'You must sign in to Item add to cart')
#         return redirect('Ecommerce:product', slug=slug)
#     else:
#         item = get_object_or_404(Item, slug=slug)
#         order_item, created = OrderItem.objects.get_or_create(
#             item=item,
#             user=request.user,
#             ordered=False
#         )
#         order_qs = Order.objects.filter(
#             user=request.user,
#             ordered=False
#         )
#         if order_qs.exists():
#             order = order_qs[0]
#             if order.items.filter(item__slug=item.slug).exists():
#                 order_item.quantity += 1
#                 order_item.save()
#                 messages.info(request, 'Item Quantity successfully updated.')
#                 return redirect("Ecommerce:product", slug=slug)
#
#             else:
#                 messages.info(request, 'Item Added to Cart')
#                 order.items.add(order_item)
#                 return redirect("Ecommerce:product", slug=slug)
#
#         else:
#             ordered_date = timezone.now()
#             order = Order.objects.create(
#                 user=request.user,

XaiphasInvestment/Ecommerce/templates/Ecommerce/investment.html
{% extends 'Ecommerce/xbase.html'%}
  {% block extrastyle %}
    <style>
        .username{
            border:solid 1px rgb(5,89,100);
            padding:5px;
            border-radius: 10px;
            background-color:white;
        }
        @media (max-width:720px){
            .balance{
                font-size:20px;
            }
            .fa-wallet{
                font-size:40px;
            }
        }
        .pass{
  text-align: center;
  border: none;
  border-bottom:solid 1px grey;
  border-radius:0;
  background:transparent;
  font-size: 16px;
  font-weight: 200;

}
.pass:focus{
  outline: none;
  transition: 0.5s;
  box-shadow: inset 0 -2px 0 0 rgb(5, 89, 100) ;
}

::placeholder{
  color:grey;
}
    </style>
{%endblock extrastyle%}

{%block body%}
    <main style="padding-top:70px;">
        <div class="container">
            <div class="">
                <a href="" class="btn btn-sm username" style="float:right;" >Hello {{request.user.username}}</a>
            </div> <br>
            <div class="alert alert-dark my-4 text-center" style="background:rgb(5,89,100); color:#fff;">
            <h2 class="balance">Your Balance is Ksh 0. </h2>
            </div>


                <div class="row">
                    <div class="col-sm-6 my-3">
                        <div class="card">
                            <div class="card-body border-to-left">
                                <div class="row">
                                    <div class="col-sm-12 text-center" >
                                        <div class="row">
                                            <div class="col-10">
                                             Make an investment. <br>
                                                <form>
                                                <input type="number" placeholder="Amount" required class="form-control pass my-3 mb-4"/>
                                                    <button type="submit" class="btn btn-sm username">Invest</button>
                                                </form>
                                            </div>
                                            <div class="col-2" style="text-align:right;">
                                            <i style="position:absolute;right:10px; color:rgb(221, 221, 221);" class="fas fa-wallet fa-3x"></i>
                                             </div>
                                        </div>

                                     </div>
                                </div>
                             </div>

                        </div>
                    </div>
                    <div class="col-sm-6 my-3">
                        <div class="card">
                            <div class="card-body border-to-left">
                                <div class="row">
                                    <div class="col-sm-12 text-center my-3">
                                          <div class="row">
                                             <div class="col-9" style="text-align:right;">

                                                Not enough money in your wallet?<br>
                                                Deposit from Mpesa.
                                             </div>
                                          <div class="col-3" style="text-align:right;">
                                          <i style="color:rgb(221, 221, 221);" class="fas fa-dollar-sign fa-3x"></i>
                                          </div>
                                          </div>
                                            <br>
                                        <a href="{% url 'Ecommerce:mpesa_deposit' %}" class="btn btn-sm username">Deposit</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>



            <div class="table-responsive text-nowrap  ">
               <center> <h4 class="my-4">Investment history</h4></center>
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>Invested</th>
                            <th>Returns</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if investement %}
                            <tr class="text-left">
                            </tr>
                    {% else %}
                    <tr>
                        <td colspan="3"><h6 class="text-muted">You Don't have any investments.</h6></td>

                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{%endblock%}

XaiphasInvestment/Ecommerce/templates/Ecommerce/item_collection.html
{% extends 'Ecommerce/xbase.html' %}
{% block extrastyle %}
    <style>
.headingtitle{
    display:block-inline;
}
.color-color-primary{
    border-left: 0.25rem solid rgb(24, 152, 168)!important;

}
.headcard{
    background:rgb(5,89,100);
    color:#fff;
}
.pass{
  text-align: center;
  border: none;
  border-bottom:solid 1px grey;
  border-radius:0;
  background:transparent;
  font-size: 16px;
  font-weight: 200;
}
.pass:focus{
  outline: none;
  transition: 0.5s;
  box-shadow: inset 0 -2px 0 0 rgb(5, 89, 100) ;
}

::placeholder{
  color:grey;
}
.login{
    background:white!important;
    color:black;
    border:solid 1px black;
    box-shadow:none!important;
    font-family:roboto!important;

}
.login:hover,.logincreate:hover{
    background:rgb(236,233,233)!important;
    color:black!important;
}
.logincreate{
    background:white!important;
    color:black;
    border:none;
    border-bottom:solid 1px black;
    box-shadow:none!important;
    font-family:roboto!important;

}

@media (max-width: 356px) {
    .login{
        padding:5px 10px!important;
    }
}

    </style>
{%endblock extrastyle%}

{% block body %}

        <div class="container"  id="page-top" style="padding-top:100px;">
           <div class="col-xl-12 col-sm-12">
                    <div class="card mb-3 headcard pt-4 border-left" >
                        <h4 class="headingtitle text-center mb-4">All Items &nbsp; <i class="fas fa-chart-line"></i></h4>
                    </div>

               <div class="table-responsive">
                   <table class="table table-striped ">
                       <thead>
                       <tr>
                            <th>#</th>
                           <th>Item</th>
                           <th>Category</th>
                           <th>Image</th>
                           <th>Status</th>
                           <th>Action</th>
                       </tr>
                       </thead>
                       <tbody>
                        {% for item in all_stock %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{item.title}}</td>
                                <td>{{item.category}}</td>
                                <td>
                                    <img src="{{item.image.url}}" class="card-img-top" style="width:30px;" alt="image">

                                </td>
                                <td>
                                    {% if item.ShowCastToCustomers %}
                                    <a href="{% url 'Ecommerce:toggleactivate' item.id %}" class="dark-grey-text">
                                        <span class="badge badge-pill blue">Active</span>
                                    </a>

                                    {% else %}
                                    <a href="{% url 'Ecommerce:toggleactivate' item.id %}" class="dark-grey-text">
                                        <span class="badge badge-pill red">Expired</span>
                                    </a>

                                    {% endif %}
                                </td>
                                <td>
                                    <span>
                                        <a href="{% url 'Ecommerce:edit_item' item.id %}">
                                            <i class="fas fa-pen" style="font-size:12px;"></i>
                                        </a>
                                    </span>&nbsp;
                                    <span>
                                        <a href="{% url 'Ecommerce:delete_item' item.id %}" onclick="return confirm('Are you sure you want to delete this?');" class="">
                                            <i class="fas fa-trash-alt ml-3" style="font-size:12px;color:red;"></i>
                                        </a>

                                              <!--modal-->

  <!--/.end-->


                                    </span>

                                </td>

                            </tr>

                        {% endfor %}
                       </tbody>
                   </table>
               </div>
       </div>


    </div>
  <footer class="page-footer text-center font-small mt-4 wow fadeIn" style="background:rgb(5,89,100);" >

<!--Call to action-->
<div class="pt-4">
<a class="scroll-to-top rounded btn btn-outline-white" href="#page-top" >Top of page
&nbsp;<i class="fas fa-angle-up"></i>
</a>

</div>
<!--/.Call to action-->

<hr class="my-4">

<!--    &lt;!&ndash; Social icons &ndash;&gt;-->
<!--    <div class="pb-4">-->
<!--      <a href="https://www.facebook.com/mdbootstrap" target="_blank">-->
<!--        <i class="fab fa-facebook-f mr-3"></i>-->
<!--      </a>-->

<!--      <a href="https://twitter.com/MDBootstrap" target="_blank">-->
<!--        <i class="fab fa-twitter mr-3"></i>-->
<!--      </a>-->

<!--      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">-->
<!--        <i class="fab fa-youtube mr-3"></i>-->
<!--      </a>-->

<!--      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">-->
<!--        <i class="fab fa-google-plus-g mr-3"></i>-->
<!--      </a>-->

<!--      <a href="https://dribbble.com/mdbootstrap" target="_blank">-->
<!--        <i class="fab fa-dribbble mr-3"></i>-->
<!--      </a>-->

<!--      <a href="https://pinterest.com/mdbootstrap" target="_blank">-->
<!--        <i class="fab fa-pinterest mr-3"></i>-->
<!--      </a>-->

<!--      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">-->
<!--        <i class="fab fa-github mr-3"></i>-->
<!--      </a>-->

<!--      <a href="http://codepen.io/mdbootstrap/" target="_blank">-->
<!--        <i class="fab fa-codepen mr-3"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--    &lt;!&ndash; Social icons &ndash;&gt;-->

<!--Copyright-->
<div class="footer-copyright py-3">
© 2019 Copyright:
<a href="#" > Xaiphas Investments. </a>
</div>
<!--/.Copyright-->

</footer>



{% endblock %}